// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Real_Estate.Models;

namespace Real_Estate.Migrations
{
    [DbContext(typeof(Real_EstateContext))]
    [Migration("20220113003356_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Real_Estate_Project.Models.Agencija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DatumOsnovanje")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("Prodadeni")
                        .HasColumnType("int");

                    b.Property<int?>("Provizija")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Agencija");
                });

            modelBuilder.Entity("Real_Estate_Project.Models.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Korisnik");
                });

            modelBuilder.Entity("Real_Estate_Project.Models.Nedviznosti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AgencijaId")
                        .HasColumnType("int");

                    b.Property<int?>("BrojOmileni")
                        .HasColumnType("int");

                    b.Property<int>("Cena")
                        .HasColumnType("int");

                    b.Property<int>("Golemina")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Kategorija")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Lokacija")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MainImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("AgencijaId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Nedviznosti");
                });

            modelBuilder.Entity("Real_Estate_Project.Models.Omileni", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int?>("NedviznostiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("NedviznostiId");

                    b.ToTable("Omileni");
                });

            modelBuilder.Entity("Real_Estate_Project.Models.Nedviznosti", b =>
                {
                    b.HasOne("Real_Estate_Project.Models.Agencija", "Agencija")
                        .WithMany("Nedviznosti")
                        .HasForeignKey("AgencijaId");

                    b.HasOne("Real_Estate_Project.Models.Korisnik", "Sopstvenik")
                        .WithMany("Nedviznosti")
                        .HasForeignKey("KorisnikId");

                    b.Navigation("Agencija");

                    b.Navigation("Sopstvenik");
                });

            modelBuilder.Entity("Real_Estate_Project.Models.Omileni", b =>
                {
                    b.HasOne("Real_Estate_Project.Models.Korisnik", "Korisnik")
                        .WithMany("Omileni")
                        .HasForeignKey("KorisnikId");

                    b.HasOne("Real_Estate_Project.Models.Nedviznosti", "Nedviznosti")
                        .WithMany("Omilen")
                        .HasForeignKey("NedviznostiId");

                    b.Navigation("Korisnik");

                    b.Navigation("Nedviznosti");
                });

            modelBuilder.Entity("Real_Estate_Project.Models.Agencija", b =>
                {
                    b.Navigation("Nedviznosti");
                });

            modelBuilder.Entity("Real_Estate_Project.Models.Korisnik", b =>
                {
                    b.Navigation("Nedviznosti");

                    b.Navigation("Omileni");
                });

            modelBuilder.Entity("Real_Estate_Project.Models.Nedviznosti", b =>
                {
                    b.Navigation("Omilen");
                });
#pragma warning restore 612, 618
        }
    }
}
